name: SWD Deployment Notes

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            **/package-lock.json

      - name: Install deps
        run: npm ci
        # If you don't commit a lockfile, switch to `npm install`

      - name: Build
        run: npm run build

      # Choose ONE deploy path you prefer:

      # 1) Netlify CLI (official, simple)
      - name: Deploy to Netlify
        run: |
          npx netlify-cli deploy --dir=./build --prod --site "$NETLIFY_SITE_ID"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      # OR keep your action (if you really want it):
      # - name: Deploy production to Netlify
      #   uses: South-Paw/action-netlify-deploy@v1.2.0
      #   with:
      #     netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
      #     build-dir: "./build"
      #     comment-on-commit: true
